### ISSUE TITLE
Get the (current) status of the File/Block volume after it is canceled

### ISSUE THREAD

**Issue by akashrajkn** [softlayer/softlayer-cli#4]
Hi, I've a question/request. How do I get the current status of a block/file volume via cli?
**Use case**: I want to know the current active volumes in my script. 
Following the [api doc](https://sldn.softlayer.com/reference/services/SoftLayer_Network_Storage/), I tried the following commands (with the outputs):
```
ibmcloud sl call-api SoftLayer_Network_Storage getVolumeStatus --init <volume_id>  # output >> PROVISION_COMPLETED
ibmcloud sl call-api SoftLayer_Network_Storage isVolumeActive --init <volume_id>  # true
```

During the provision process, the first command either outputs `PROVISION_INITIATED` or `PROVISION_COMPLETED` which is nice to find out whether is volume is ready. In the GUI, the status is `Active`

However, after I cancel a (hourly billing rate) volume, in the GUI: Classic infrastructure >> File Storage, the status shown is `Cancellation pending`. But if I execute the above two commands, I still get the status as `PROVISION COMPLETED` and `true`. Is there a way to get the status that is shown in the gui?

Cheers and thank you in advance :)

**Comment by allmightyspiff** [comment]
The GUI does a lot of things that mask the complexities of the API. If you want to tell if a volume is ready to use, I think either of the 2 API calls you mentioned work. You might also want to be aware of 
`ibmcloud.exe  sl call-api SoftLayer_Network_Storage getActiveTransactions   --init 202633164`
Any volume with an active transaction will likely not be available for use. This will be things like provisioning transactions, or replication transactions. If it returns an empty array, thats another good indicator the volume is ready to use.

For a pending cancellation, you need to check the billingItem->cancellationDate field.

```
$  ibmcloud.exe  sl call-api SoftLayer_Network_Storage  getObject --init 202633164 --mask="mask[id,billingItem[id,cancellationDate]]"
2022/03/02 09:01:08 [DEBUG] Request URL:  GET https://api.softlayer.com/rest/v3.1/SoftLayer_Network_Storage/202633164.json?objectMask=mask%5Bid%2CbillingItem%5Bid%2CcancellationDate%5D%5D
2022/03/02 09:01:08 [DEBUG] Parameters:
2022/03/02 09:01:08 [DEBUG] Status Code:  200
2022/03/02 09:01:08 [DEBUG] Response:  {"id":202633164,"billingItem":{"cancellationDate":"2022-03-04T00:00:00-06:00","id":792575188}}
{
        "id": 202633164,
        "billingItem": {
                "cancellationDate": "2022-03-04T00:00:00-06:00",
                "id": 792575188
        }
}

$  ibmcloud.exe  sl call-api SoftLayer_Network_Storage  getObject --init 235854228 --mask="mask[id,billingItem[id,cancellationDate]]"
2022/03/02 09:01:40 [DEBUG] Request URL:  GET https://api.softlayer.com/rest/v3.1/SoftLayer_Network_Storage/235854228.json?objectMask=mask%5Bid%2CbillingItem%5Bid%2CcancellationDate%5D%5D
2022/03/02 09:01:40 [DEBUG] Parameters:
2022/03/02 09:01:41 [DEBUG] Status Code:  200
2022/03/02 09:01:41 [DEBUG] Response:  {"id":235854228,"billingItem":{"cancellationDate":null,"id":849126538}}
{
        "id": 235854228,
        "billingItem": {
                "cancellationDate": null,
                "id": 849126538
        }
}
```

If there is a date there, that volume will be cancelled on that date. Otherwise that field will be empty. Hope that helps.

**Comment by akashrajkn** [comment]
Thanks for a super quick reply :) 

I wasn't aware of `getActiveTransactions`. With that, I can find the cancellation status
